#! Project information
site_name: Menoreh
site_author: Nanang Prasetya
site_description: >-
  Write your documentation in Markdown and create a professional static site in
  minutes – searchable, customizable, for all devices

#! Repository
repo_name: rekat-docs
repo_url: https://github.com/Nanangprasetya/rekat-docs

#! Copyright
copyright: Copyright &copy; 2023 Nanang Prasetya

#! Navigation menu
nav:
  - Home:
    - index.md
  - Getting started:
    - Installing: documentation/started.md
    - Extension: documentation/extention.md
  - Repo: documentation/started.md

#! Theme
theme:
  name: material
  custom_dir: overrides
  logo: assets/images/menoreh_logo.png
  features:
    - tabs
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.tabs.link
    - content.code.annotate
    - content.tooltips
    - search.highlight
    - search.share
    - search.suggest
    - announce.dismiss
    - toc.follow
  icon:
    repo: fontawesome/brands/github
  font:
    text: Inter
  include_sidebar: yes
  include_search_page: false
  search_index_only: true
  palette:
    - scheme: default
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
#! Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

#! Plugin
plugins:
  - search
  - mike
  - pdf-export
  - git-authors
  - git-committers:
      repository: Nanangprasetya/rekat-docs
      branch: master
  - git-revision-date-localized:
      type: datetime
      enable_creation_date: true
      fallback_to_build_date: true
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true

#! Extra CSS
extra_css:
  - stylesheets/extra.css

#! Customization 
extra:
  version:
    provider: mike